/**
 * skill-autogen.ts — full-Hermes autonomous skill creation (Phase: autonomy).
 *
 * Procedural rules that keep proving out (accessCount >= threshold across
 * reconcile REINFORCEs and recalls) auto-become ENABLED skills, flagged
 * source:'system'. Tier is LOCKED to 'read-only' — privilege escalation is
 * the one autonomy deliberately withheld; a human raises the tier manually.
 * Veto: disable/delete the skill in the UI (the promotedSkillSlug marker
 * stamped into the memory prevents resurrection), or turn the flag off.
 * Never throws.
 */

import { getPrismaClient } from '@/lib/db/pg-config';
import { getSkillRepository } from '@/lib/db/repository-factory';
import { slugify } from '@/lib/skill-service';
import { getMemoryService } from './memory-service';

export function autoSkillCreationEnabled(): boolean {
    const v = process.env.AUTO_SKILL_CREATION_ENABLED?.toLowerCase();
    return !(v === 'false' || v === '0');
}

export function autoSkillMaturityThreshold(): number {
    const n = Number(process.env.AUTO_SKILL_MATURITY_THRESHOLD);
    return Number.isFinite(n) && n > 0 ? n : 3;
}

const MAX_PROMOTIONS_PER_RUN = 5;

function humanize(key: string): string {
    return key.split(/[-_]+/).filter(Boolean).map((w) => (w[0]?.toUpperCase() ?? '') + w.slice(1)).join(' ');
}

export async function autoCreateSkillsFromMaturedRules(params: {
    tenantId: string;
    threadId?: string;
}): Promise<number> {
    if (!autoSkillCreationEnabled()) return 0;
    let created = 0;
    try {
        const prisma = getPrismaClient();
        const threshold = autoSkillMaturityThreshold();
        // Raw SQL is NOT tenant-intercepted — tenantId bound explicitly.
        const candidates = await prisma.$queryRaw<Array<{
            id: string; key: string; value: Record<string, unknown>;
            sourceThreadId: string | null; accessCount: number;
        }>>`
            SELECT "id","key","value","sourceThreadId","accessCount"
            FROM agent_memories
            WHERE "tenantId" = ${params.tenantId}
              AND "kind" = 'PROCEDURAL'
              AND "supersededById" IS NULL
              AND "accessCount" >= ${threshold}
              AND ("value"->>'promotedSkillSlug') IS NULL
            ORDER BY "accessCount" DESC
            LIMIT ${MAX_PROMOTIONS_PER_RUN}
        `;
        if (!candidates.length) return 0;

        const repo = getSkillRepository();
        const svc = getMemoryService();
        for (const c of candidates) {
            try {
                const v = c.value as { instruction?: string; trigger?: string; evidence?: string };
                if (!v?.instruction || !v?.trigger) continue;
                const slug = slugify(c.key);
                if (!slug) continue;
                const stamp = () => svc.update(params.tenantId, c.id, { ...c.value, promotedSkillSlug: slug });

                const existing = await repo.getBySlug(params.tenantId, slug);
                if (existing) {
                    console.log(`🎯 [AUTO-SKILL] Rule '${c.key}' matured but skill '${slug}' already exists — marking promoted`);
                    await stamp();
                    continue;
                }
                try {
                    await repo.create(params.tenantId, {
                        slug,
                        name: humanize(c.key),
                        description: v.trigger,
                        tier: 'read-only',
                        content:
                            `## Rule\n${v.instruction}\n\n` +
                            `## When it applies\n${v.trigger}\n\n` +
                            `## Why (evidence)\n${v.evidence || '(not recorded)'}\n\n` +
                            `_Auto-generated by the agent from a matured procedural rule (accessCount ${c.accessCount})._`,
                        source: 'system',
                        isEnabled: true,
                        createdBy: null,
                        sourceRunId: params.threadId ?? c.sourceThreadId,
                    });
                    created++;
                    console.log(`🎯 [AUTO-SKILL] Rule '${c.key}' matured (accessCount=${c.accessCount}) → created skill '${slug}' (system, enabled, read-only)`);
                } catch (err) {
                    if ((err as { code?: string })?.code !== 'P2002') throw err;
                    console.log(`🎯 [AUTO-SKILL] Skill '${slug}' created concurrently — marking promoted`);
                }
                await stamp();
            } catch (err: any) {
                console.warn(`🎯 [AUTO-SKILL] Promotion failed for '${c.key}' (non-fatal): ${err?.message ?? err}`);
            }
        }
    } catch (err: any) {
        console.warn(`🎯 [AUTO-SKILL] Maturity check failed (non-fatal): ${err?.message ?? err}`);
    }
    return created;
}
