version: 0.2
env:
  variables:
    PULUMI_CONFIG_PASSPHRASE: ""
    AWS_DEFAULT_REGION: ap-south-1
phases:
  build:
    commands:
      - cd infra/networking && pulumi preview --stack prod --non-interactive --diff
      - cd ../compute && pulumi preview --stack prod --non-interactive --diff
