-- ═══════════════════════════════════════════════════════════════════════════════
-- Fargate Spot Guard (SG-001) — initial schema
--
-- Ported from the standalone CDK/DynamoDB system (cdk-ecs-fargate-spot-automation).
-- Five new tables plus five additive columns on `accounts`.
--
-- ⚠️  HAND-AUTHORED — DO NOT REGENERATE THIS FILE WITH `prisma migrate dev`.
--
-- Two independent reasons:
--
--   1. Prisma 5 does not emit CHECK constraints, and every string enum in this
--      feature relies on one (house convention — see
--      20260713070000_agent_ops_check_constraints_new_values). The declared source
--      of truth for these value sets is the union types in
--      apps/web-ui/lib/db/repositories/spot-guard/interface.ts; keep them in sync.
--
--   2. More importantly, `prisma migrate dev` emits DESTRUCTIVE drift-correction
--      statements that have nothing to do with Spot Guard. The autogenerated diff
--      for this very change opened with "You are about to drop the column
--      `contentHash` on the `inventory_resources` table. All the data in the column
--      will be lost." and wanted to:
--          DROP INDEX "agent_memories_embedding_hnsw"
--          DROP INDEX "idx_inventory_search_vector"
--          DROP INDEX "idx_kb_document_chunks_embedding"
--          ALTER TABLE "inventory_resources" DROP COLUMN "contentHash"
--          ALTER TABLE "inventory_sync_status" ALTER COLUMN "errors" SET DEFAULT ...
--      Those three indexes were created by raw SQL in earlier migrations and cannot
--      be expressed in schema.prisma, so Prisma reads them as extraneous and drops
--      them. Applying that would silently destroy agent-memory vector search,
--      inventory full-text search, and a column of data. All five statements were
--      stripped; only the additive Spot Guard DDL below was kept.
--
--      (The underlying schema drift is pre-existing and unrelated to this feature.
--      It deserves its own fix — either by declaring those indexes in
--      schema.prisma where possible, or by documenting them as raw-SQL-managed.)
--
-- This migration is additive-only: no DROP, no RENAME, no ALTER COLUMN, no type
-- change to any pre-existing column. Every column added to `accounts` is nullable or
-- has a default, so it is backfill-free and every existing row is immediately valid.
--
-- WHY TIMESTAMPTZ(3) AND NOT TIMESTAMP(3)
-- Every timestamp here is TIMESTAMPTZ(3), which departs from the rest of this schema
-- (Prisma's DateTime default is timestamp(3), i.e. WITHOUT time zone). That default is
-- wrong for storing instants and it bit this feature during development:
--
--   '2026-07-20T00:00:00.000+05:30'::timestamp   -> 2026-07-20 00:00:00   (offset DISCARDED)
--   '2026-07-20T00:00:00.000+05:30'::timestamptz -> 2026-07-19 18:30:00+00 (correct instant)
--
-- node-postgres serialises a JS Date with the CLIENT's local offset, so a
-- timestamp-without-zone column stores local wall-clock rather than the instant. Writes
-- and reads stay self-consistent as long as every process shares one timezone — true on
-- ECS (TZ=UTC), false on a developer machine — which makes duration arithmetic
-- environment-dependent. These columns feed the Spot-vs-On-Demand hours report, whose
-- whole job is interval arithmetic, so correctness there is not optional. The bug
-- surfaced as six failing clipping tests on an IST machine and would have been invisible
-- in CI.
--
-- The rest of the schema has the same latent issue; fixing it is a separate change with
-- its own data-migration considerations and is deliberately not attempted here.
-- ═══════════════════════════════════════════════════════════════════════════════

-- ── AlterTable: additive Spot Guard columns on the existing accounts table ────
-- spotAutomationEnabled  drives the hub event-bus resource-policy allowlist.
-- spotAutomationStatus   is SEPARATE from connectionStatus on purpose: that column
--                        has two writers (web-ui validateAccount AND the workers
--                        discovery job, which derives it), so a Spot value written
--                        there would be clobbered by the next nightly scan. A
--                        customer who has not opted in is also not a broken
--                        connection and must not surface as an error.
ALTER TABLE "accounts" ADD COLUMN     "spotAutomationCheckedAt" TIMESTAMPTZ(3),
ADD COLUMN     "spotAutomationEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "spotAutomationError" TEXT,
ADD COLUMN     "spotAutomationStatus" TEXT NOT NULL DEFAULT 'not_configured',
ADD COLUMN     "templateVersion" INTEGER;

-- CreateTable
CREATE TABLE "spot_guard_services" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "accountId" TEXT NOT NULL,
    "region" TEXT NOT NULL,
    "clusterName" TEXT NOT NULL,
    "serviceName" TEXT NOT NULL,
    "clusterArn" TEXT,
    "serviceArn" TEXT,
    "desiredStrategy" JSONB NOT NULL DEFAULT '[]',
    "observedStrategy" JSONB NOT NULL DEFAULT '[]',
    "observedAt" TIMESTAMPTZ(3),
    "capacityState" TEXT NOT NULL DEFAULT 'unknown',
    "managementState" TEXT NOT NULL DEFAULT 'managed',
    "restorePending" BOOLEAN NOT NULL DEFAULT false,
    "lastFallbackAt" TIMESTAMPTZ(3),
    "lastRestoreAt" TIMESTAMPTZ(3),
    "lastRestoreAttemptAt" TIMESTAMPTZ(3),
    "lastFailedAt" TIMESTAMPTZ(3),
    "consecutiveFailures" INTEGER NOT NULL DEFAULT 0,
    "backoffUntil" TIMESTAMPTZ(3),
    "desiredCount" INTEGER,
    "runningCount" INTEGER,
    "serviceStatus" TEXT,
    "albTargetGroupArns" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "interruptionCount" INTEGER NOT NULL DEFAULT 0,
    "placementFailureCount" INTEGER NOT NULL DEFAULT 0,
    "fallbackCount" INTEGER NOT NULL DEFAULT 0,
    "restoreCount" INTEGER NOT NULL DEFAULT 0,
    "enabledBy" TEXT,
    "enabledAt" TIMESTAMPTZ(3),
    "disabledBy" TEXT,
    "disabledAt" TIMESTAMPTZ(3),
    "lastEventAt" TIMESTAMPTZ(3),
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "spot_guard_services_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "spot_guard_events" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "spotServiceId" TEXT,
    "accountId" TEXT NOT NULL,
    "region" TEXT NOT NULL,
    "clusterName" TEXT NOT NULL,
    "serviceName" TEXT NOT NULL,
    "eventType" TEXT NOT NULL,
    "severity" TEXT NOT NULL DEFAULT 'info',
    "sourceEventId" TEXT,
    "taskArn" TEXT,
    "capacityProvider" TEXT,
    "fromCapacity" TEXT,
    "toCapacity" TEXT,
    "stopCode" TEXT,
    "stoppedReason" TEXT,
    "strategyBefore" JSONB,
    "strategyAfter" JSONB,
    "message" TEXT NOT NULL DEFAULT '',
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "notifiedSlack" BOOLEAN NOT NULL DEFAULT false,
    "slackError" TEXT,
    "actor" TEXT NOT NULL DEFAULT 'system',
    "occurredAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "spot_guard_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "spot_guard_task_sessions" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "accountId" TEXT NOT NULL,
    "region" TEXT NOT NULL,
    "clusterName" TEXT NOT NULL,
    "serviceName" TEXT NOT NULL,
    "taskArn" TEXT NOT NULL,
    "capacityProvider" TEXT,
    "capacityType" TEXT NOT NULL,
    "startedAt" TIMESTAMPTZ(3) NOT NULL,
    "stoppedAt" TIMESTAMPTZ(3),
    "durationSeconds" DOUBLE PRECISION,
    "reportDate" TEXT,
    "stopCode" TEXT,
    "stoppedReason" TEXT,
    "interrupted" BOOLEAN NOT NULL DEFAULT false,
    "orphaned" BOOLEAN NOT NULL DEFAULT false,
    "isOpen" BOOLEAN NOT NULL DEFAULT true,
    "interruptionHandledAt" TIMESTAMPTZ(3),
    "cpuUnits" INTEGER,
    "memoryMiB" INTEGER,
    "expiresAt" TIMESTAMPTZ(3) NOT NULL,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "spot_guard_task_sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "spot_guard_alert_dedup" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "dedupKey" TEXT NOT NULL,
    "alertType" TEXT NOT NULL,
    "windowSeconds" INTEGER NOT NULL,
    "firstSeenAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastSeenAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "hitCount" INTEGER NOT NULL DEFAULT 1,
    "suppressedCount" INTEGER NOT NULL DEFAULT 0,
    "expiresAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "spot_guard_alert_dedup_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "spot_guard_actions" (
    "id" TEXT NOT NULL,
    "accountId" TEXT NOT NULL,
    "clusterArn" TEXT NOT NULL,
    "serviceName" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "windowStart" TIMESTAMPTZ(3) NOT NULL,
    "actingTenant" TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "spot_guard_actions_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "spot_guard_services_tenantId_capacityState_idx" ON "spot_guard_services"("tenantId", "capacityState");

-- CreateIndex
CREATE INDEX "spot_guard_services_tenantId_managementState_idx" ON "spot_guard_services"("tenantId", "managementState");

-- CreateIndex
CREATE INDEX "spot_guard_services_tenantId_restorePending_backoffUntil_idx" ON "spot_guard_services"("tenantId", "restorePending", "backoffUntil");

-- CreateIndex
CREATE INDEX "spot_guard_services_tenantId_accountId_region_idx" ON "spot_guard_services"("tenantId", "accountId", "region");

-- CreateIndex
CREATE UNIQUE INDEX "spot_guard_services_tenantId_accountId_region_clusterName_s_key" ON "spot_guard_services"("tenantId", "accountId", "region", "clusterName", "serviceName");

-- CreateIndex
CREATE INDEX "spot_guard_events_tenantId_occurredAt_idx" ON "spot_guard_events"("tenantId", "occurredAt");

-- CreateIndex
CREATE INDEX "spot_guard_events_tenantId_eventType_occurredAt_idx" ON "spot_guard_events"("tenantId", "eventType", "occurredAt");

-- CreateIndex
CREATE INDEX "spot_guard_events_tenantId_spotServiceId_occurredAt_idx" ON "spot_guard_events"("tenantId", "spotServiceId", "occurredAt");

-- CreateIndex
CREATE INDEX "spot_guard_events_expiresAt_idx" ON "spot_guard_events"("expiresAt");

-- CreateIndex
-- NULLs are distinct in a Postgres UNIQUE index, so manual/user-initiated events
-- (which carry no sourceEventId) are unconstrained — intended.
CREATE UNIQUE INDEX "spot_guard_events_tenantId_sourceEventId_eventType_key" ON "spot_guard_events"("tenantId", "sourceEventId", "eventType");

-- CreateIndex
CREATE INDEX "spot_guard_task_sessions_tenantId_reportDate_idx" ON "spot_guard_task_sessions"("tenantId", "reportDate");

-- CreateIndex
CREATE INDEX "spot_guard_task_sessions_tenantId_isOpen_startedAt_idx" ON "spot_guard_task_sessions"("tenantId", "isOpen", "startedAt");

-- CreateIndex
CREATE INDEX "spot_guard_task_sessions_tenantId_accountId_region_clusterN_idx" ON "spot_guard_task_sessions"("tenantId", "accountId", "region", "clusterName", "serviceName", "startedAt");

-- CreateIndex
CREATE INDEX "spot_guard_task_sessions_tenantId_startedAt_stoppedAt_idx" ON "spot_guard_task_sessions"("tenantId", "startedAt", "stoppedAt");

-- CreateIndex
CREATE INDEX "spot_guard_task_sessions_expiresAt_idx" ON "spot_guard_task_sessions"("expiresAt");

-- CreateIndex
CREATE UNIQUE INDEX "spot_guard_task_sessions_tenantId_taskArn_key" ON "spot_guard_task_sessions"("tenantId", "taskArn");

-- CreateIndex
CREATE INDEX "spot_guard_alert_dedup_expiresAt_idx" ON "spot_guard_alert_dedup"("expiresAt");

-- CreateIndex
CREATE INDEX "spot_guard_alert_dedup_tenantId_alertType_idx" ON "spot_guard_alert_dedup"("tenantId", "alertType");

-- CreateIndex
CREATE UNIQUE INDEX "spot_guard_alert_dedup_tenantId_dedupKey_key" ON "spot_guard_alert_dedup"("tenantId", "dedupKey");

-- CreateIndex
CREATE INDEX "spot_guard_actions_expiresAt_idx" ON "spot_guard_actions"("expiresAt");

-- CreateIndex
CREATE UNIQUE INDEX "spot_guard_actions_accountId_clusterArn_serviceName_action__key" ON "spot_guard_actions"("accountId", "clusterArn", "serviceName", "action", "windowStart");

-- CreateIndex
-- Supports the bus-policy reconciler's cross-tenant
-- SELECT DISTINCT "accountId" WHERE active AND "spotAutomationEnabled".
CREATE INDEX "accounts_active_spotAutomationEnabled_idx" ON "accounts"("active", "spotAutomationEnabled");

-- ═══════════════════════════════════════════════════════════════════════════════
-- CHECK constraints for string enums (Prisma 5 cannot emit these).
-- Source of truth: the union types in
-- apps/web-ui/lib/db/repositories/spot-guard/interface.ts and
-- apps/workers/src/jobs/spot-guard/types.ts.
-- ═══════════════════════════════════════════════════════════════════════════════

ALTER TABLE "accounts" ADD CONSTRAINT "accounts_spot_automation_status_check"
    CHECK ("spotAutomationStatus" IN ('not_configured', 'pending', 'ready', 'error'));

ALTER TABLE "spot_guard_services" ADD CONSTRAINT "spot_guard_services_capacity_state_check"
    CHECK ("capacityState" IN ('spot', 'on_demand', 'mixed', 'unknown'));

ALTER TABLE "spot_guard_services" ADD CONSTRAINT "spot_guard_services_management_state_check"
    CHECK ("managementState" IN ('managed', 'unmanaged', 'opted_out'));

ALTER TABLE "spot_guard_services" ADD CONSTRAINT "spot_guard_services_service_status_check"
    CHECK ("serviceStatus" IS NULL OR "serviceStatus" IN ('ACTIVE', 'DRAINING', 'INACTIVE'));

-- A negative counter can only come from a decrement bug; fail loudly instead.
ALTER TABLE "spot_guard_services" ADD CONSTRAINT "spot_guard_services_counters_nonneg_check"
    CHECK ("consecutiveFailures" >= 0 AND "interruptionCount" >= 0
       AND "placementFailureCount" >= 0 AND "fallbackCount" >= 0 AND "restoreCount" >= 0);

ALTER TABLE "spot_guard_events" ADD CONSTRAINT "spot_guard_events_event_type_check"
    CHECK ("eventType" IN (
        'interruption', 'placement_failure', 'fallback_applied',
        'restore_attempted', 'restore_succeeded', 'restore_failed',
        'spot_enabled', 'spot_disabled', 'unmanaged',
        'capacity_transition', 'alb_predrain', 'governance_skip', 'backoff_skip'
    ));

ALTER TABLE "spot_guard_events" ADD CONSTRAINT "spot_guard_events_severity_check"
    CHECK ("severity" IN ('info', 'warning', 'critical'));

ALTER TABLE "spot_guard_events" ADD CONSTRAINT "spot_guard_events_from_capacity_check"
    CHECK ("fromCapacity" IS NULL OR "fromCapacity" IN ('spot', 'on_demand'));

ALTER TABLE "spot_guard_events" ADD CONSTRAINT "spot_guard_events_to_capacity_check"
    CHECK ("toCapacity" IS NULL OR "toCapacity" IN ('spot', 'on_demand'));

ALTER TABLE "spot_guard_task_sessions" ADD CONSTRAINT "spot_guard_task_sessions_capacity_type_check"
    CHECK ("capacityType" IN ('spot', 'on_demand'));

-- The reference implementation stored duration as a STRING and re-parsed it with
-- float(); enforcing non-negative numerics here makes that class of bug impossible.
ALTER TABLE "spot_guard_task_sessions" ADD CONSTRAINT "spot_guard_task_sessions_duration_check"
    CHECK ("durationSeconds" IS NULL OR "durationSeconds" >= 0);

-- An open session has no stoppedAt; a closed one must have it. Keeps the
-- open→closed state machine honest at the storage layer.
ALTER TABLE "spot_guard_task_sessions" ADD CONSTRAINT "spot_guard_task_sessions_open_consistency_check"
    CHECK (("isOpen" = true AND "stoppedAt" IS NULL) OR ("isOpen" = false AND "stoppedAt" IS NOT NULL));

ALTER TABLE "spot_guard_alert_dedup" ADD CONSTRAINT "spot_guard_alert_dedup_alert_type_check"
    CHECK ("alertType" IN (
        'interruption', 'placement_failure', 'remediation', 'fallback',
        'recovery', 'restore_attempt', 'restore_failed', 'spot_enabled', 'spot_disabled'
    ));

-- windowSeconds 0 means "never dedup" (user-initiated alerts always notify).
ALTER TABLE "spot_guard_alert_dedup" ADD CONSTRAINT "spot_guard_alert_dedup_window_check"
    CHECK ("windowSeconds" >= 0 AND "windowSeconds" <= 86400);

ALTER TABLE "spot_guard_actions" ADD CONSTRAINT "spot_guard_actions_action_check"
    CHECK ("action" IN ('fallback', 'restore', 'alb_predrain', 'enable_spot', 'disable_spot'));
