config:
  aws:region: us-east-1
  nucleus-compute:appUrl: https://d11lr8aqp8vqde.cloudfront.net
  nucleus-compute:subscriptionEmails: ""
  nucleus-compute:discoveryImageUri: ""
  nucleus-compute:crossAccountRoleName: "NucleusAccess"
  nucleus-compute:vectorBucketName: ""
  nucleus-compute:webUiImageUri: "970547372609.dkr.ecr.us-east-1.amazonaws.com/nucleus-cloud-ops-web-ui:latest"
  # nextauthSecret: run: cd infra/compute && pulumi config set --secret nextauthSecret "change-in-production"
  # dbPassword: run: cd infra/compute && pulumi config set --secret dbPassword "your-password-here" --stack prod

  nucleus-compute:nextauthSecret:
    secure: v1:WvdMHHoiYq5ViD1H:hQgCfrd9Lu5Pj410uRyGzkedLGyiq2uXFH4afXfvCAh+mIau
  nucleus-compute:dbPassword:
    secure: v1:Q3864iBfbpzejBUj:9UG1qQ4PK539GdozL4BUbXoPpTxdzJKkK98ulBoOkDH1FS/uS3r1m/nR+3T98yI=
secretsprovider: awskms://alias/pulumi-secrets?region=us-east-1
encryptedkey: AQICAHgKGeti15Vdcfk9By77gHbFq3IykDNyF5lB23hWk4E3nQHc6Ho6T+iM2Lo+gStzUwciAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMSen7cscQDJw7g6O0AgEQgDtbSSbyQ9dbVjvoDRwP98DBGvCn3npSNyqIH/WM7bUniLKiQRJs1gEPJYRNPm56IG9vCpJ8IE2G5KHweQ==
